server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: hello
        uri: http://localhost:8084
        predicates:
          - Path=/hello/**
        filters:
          - RewritePath=/hello/(?<path>.*), /$\{path}
      - id: world
        uri: lb://world
        predicates:
          - Path=/world/**
        filters:
          - RewritePath=/world/(?<path>.*), /$\{path}
        
management:
  endpoints:
    web:
      exposure:
        include: gateway
