server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: product
        uri: lb://product
        predicates:
          - Path=/product/**, /product
        filters:
          - RewritePath=/product/(?<path>.*), /$\{path}
          - RewritePath=/product, /
      - id: review
        uri: lb://review
        predicates:
          - Path=/review/**, /review
        filters:
          - RewritePath=/review/(?<path>.*), /$\{path}
          - RewritePath=/review, /
        
management:
  endpoints:
    web:
      exposure:
        include: gateway
