server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: product
        uri: lb://product
        predicates:
          - Path=/products/**, /products
        filters:
          - RewritePath=/products/(?<path>.*), /$\{path}
          - RewritePath=/products, /
      - id: review
        uri: lb://review
        predicates:
          - Path=/reviews/**, /reviews
        filters:
          - RewritePath=/reviews/(?<path>.*), /$\{path}
          - RewritePath=/reviews, /
        
management:
  endpoints:
    web:
      exposure:
        include: gateway
